//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSportsEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id_comment { get; set; }
        public string comment_content { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_article { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual user user { get; set; }
    }
}
