//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSportsEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebTheThaoEntities : DbContext
    {
        public WebTheThaoEntities()
            : base("name=WebTheThaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_filter_cmt_article_Result> sp_filter_cmt_article(Nullable<int> id_article)
        {
            var id_articleParameter = id_article.HasValue ?
                new ObjectParameter("id_article", id_article) :
                new ObjectParameter("id_article", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_filter_cmt_article_Result>("sp_filter_cmt_article", id_articleParameter);
        }
    
        public virtual ObjectResult<sp_find_user_by_username_Result> sp_find_user_by_username(string usernameFind)
        {
            var usernameFindParameter = usernameFind != null ?
                new ObjectParameter("usernameFind", usernameFind) :
                new ObjectParameter("usernameFind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_find_user_by_username_Result>("sp_find_user_by_username", usernameFindParameter);
        }
    
        public virtual ObjectResult<sp_get_all_category_article_Result> sp_get_all_category_article()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_category_article_Result>("sp_get_all_category_article");
        }
    
        public virtual ObjectResult<sp_get_all_users_Result> sp_get_all_users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_users_Result>("sp_get_all_users");
        }
    
        public virtual int sp_get_article_and_category()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_article_and_category");
        }
    
        public virtual int sp_get_article_by_category(Nullable<int> id_category)
        {
            var id_categoryParameter = id_category.HasValue ?
                new ObjectParameter("id_category", id_category) :
                new ObjectParameter("id_category", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_article_by_category", id_categoryParameter);
        }
    
        public virtual int sp_get_list_id_article_by_category(Nullable<int> id_category)
        {
            var id_categoryParameter = id_category.HasValue ?
                new ObjectParameter("id_category", id_category) :
                new ObjectParameter("id_category", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_list_id_article_by_category", id_categoryParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_get_article_category_Result> sp_get_article_category()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_article_category_Result>("sp_get_article_category");
        }
    
        public virtual ObjectResult<sp_get_all_article_category_Result> sp_get_all_article_category()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_article_category_Result>("sp_get_all_article_category");
        }
    
        public virtual ObjectResult<sp_get_all_article_by_category_Result> sp_get_all_article_by_category(Nullable<int> id_cate)
        {
            var id_cateParameter = id_cate.HasValue ?
                new ObjectParameter("id_cate", id_cate) :
                new ObjectParameter("id_cate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_article_by_category_Result>("sp_get_all_article_by_category", id_cateParameter);
        }
    
        public virtual ObjectResult<sp_get_article_and_category1_Result> sp_get_article_and_category1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_article_and_category1_Result>("sp_get_article_and_category1");
        }
    
        public virtual ObjectResult<sp_get_article_by_category_1_Result> sp_get_article_by_category_1(Nullable<int> id_cate)
        {
            var id_cateParameter = id_cate.HasValue ?
                new ObjectParameter("id_cate", id_cate) :
                new ObjectParameter("id_cate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_article_by_category_1_Result>("sp_get_article_by_category_1", id_cateParameter);
        }
    }
}
